bookstore/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

users/urls.py
from django.urls import path
from .views import SignupView, SignupUpdateView

app_name = 'users'
urlpatterns = [
    path('', SignupView.as_view(), name='sign_up'),
    path('update-account/<int:pk>/',
         SignupUpdateView.as_view(), name='update_users')
]

# users/update-account/

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class CustomUser(AbstractUser):
    DEGREE_CHOICE = (
        ('Graduated', 'Graduated'),
        ('Freshman', 'Freshman'),
        ('Master Degree', 'Master Degree'),
        ('PHD', 'PHD')
    )

    phoneNumber = models.CharField(
        verbose_name='Phone Number', max_length=20, null=True, blank=True)
    jobTitle = models.CharField(
        verbose_name='Job Title', max_length=200, null=True, blank=True)
    zipCode = models.CharField(
        verbose_name='Zip Code', max_length=10, null=True, blank=True)
    degree = models.CharField(
        max_length=15, choices=DEGREE_CHOICE, null=True, blank=True)

users/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm, UserChangeForm


# The password field is implicitly included by default and
# so does not need to be explicitly named here as well.
class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'phoneNumber',
                  'jobTitle', 'zipCode', 'degree']


class CustomUserChangeForm(UserChangeForm):
    class Meta:
        model = get_user_model()
        fields = ['username', 'email', 'phoneNumber',
                  'jobTitle', 'zipCode', 'degree']

users/views.py
from django.shortcuts import render
from django.views.generic import CreateView, UpdateView
from django.contrib.auth import get_user_model
from .forms import CustomUserCreationForm, CustomUserChangeForm

CustomUser = get_user_model()


class SignupView(CreateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'sign_up.html'


class SignupUpdateView(UpdateView):
    model = CustomUser
    form_class = CustomUserCreationForm
    template_name = 'update_user_info.html'

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">

    {% block head %}

    {% endblock head %}
</head>

<body>

    <nav class="navbar navbar-expand-sm bg-dark d-flex justify-content-end navbar-dark">
        <!-- Links -->
        <ul class="navbar-nav">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:sign_up' %}">Sign up</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:update_users' 3 %}">Update User 3</a>
            </li>
        </ul>
    </nav>
    {% block content %}


    {% endblock content %}


    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Popper JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/sign_up.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block head %}
<title>Sign up</title>
{% endblock head %}


{% block content %}
<form action="." method="POST" class="signup-form">
    <h1>Create account</h1>
    <hr>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Create Account" class='btn btn-block btn-primary'>
</form>
{% endblock content %}

templates/update_user_info.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block head %}
<title>Update {{ user.username }}</title>
{% endblock head %}


{% block content %}
<form action="." method="POST" class="signup-form">
    <h1>Update {{ user.username }} account</h1>
    <hr>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Create Account" class='btn btn-block btn-warning'>
</form>
{% endblock content %}